AY2122S1-CS2103T-W16-4/tp

- docs/UserGuide.md
> Add features "edit task" and "view task" into the user guide

- docs/UserGuide.md
> Add more features and Quick start to User Guide 

- README.md
Fix #23 
The rest of README.md still need to be updated by @kvihashini
> Update the acknowledgement of README.md

- README.md
> Update README to match project

- docs/UserGuide.md
> Update command summary in the user guide

- docs/UserGuide.md
But since those sections are already generously added, these are just some minor mistake fixes
> Adds 'help' and 'add student' to UserGuide.md

- docs/UserGuide.md
The last pull request was a mistake. Sorry.
> Correct changes to 'help' and 'add student'

- docs/DeveloperGuide.md
> Add value proposition and more user stories to Developer Guide

- docs/DeveloperGuide.md
> Adds use cases to DeveloperGuide.md

- src/main/java/seedu/address/logic/commands/persons/ViewPersonCommand.java
- src/main/java/seedu/address/logic/parser/persons/PersonCommandsParser.java
- src/main/java/seedu/address/logic/parser/persons/ViewPersonCommandParser.java
- src/test/java/seedu/address/logic/commands/ViewPersonCommandTest.java
- src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
- src/test/java/seedu/address/logic/parser/ViewPersonCommandParserTest.java
> Refactor code to add 'view' command for students

- src/main/java/seedu/address/model/task/Deadline.java
... from `String` to `LocalDate`.
Fix #59.
> Change the type of the actual deadline stored in `task.Deadline`

- src/main/java/seedu/address/logic/commands/persons/PersonAddLessonCommand.java
- src/main/java/seedu/address/logic/parser/persons/PersonAddLessonParser.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/ReadOnlyAddressBook.java
- src/main/java/seedu/address/model/lesson/Lesson.java
- src/main/java/seedu/address/model/lesson/Timeslot.java
- src/main/java/seedu/address/storage/JsonAdaptedLesson.java
- src/test/java/seedu/address/model/AddressBookTest.java
- src/test/java/seedu/address/model/lesson/LessonTest.java
- src/test/java/seedu/address/testutil/LessonBuilder.java
Issue #84 
This was done by looping through the Persons and then retrieving lessons from each Person.
> Retrieve all lessons list from addressbook

- src/main/java/seedu/address/logic/commands/persons/EditPersonCommand.java
- src/main/java/seedu/address/logic/parser/persons/AddPersonCommandParser.java
- src/main/java/seedu/address/model/person/Exam.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedPerson.java
- src/test/java/seedu/address/testutil/PersonBuilder.java
Issue #86 
Add a List<Exam> to person model so that we can retrieve their exam dates in the future.
TODO: Add commands to add/remove these exams.
> Add List<Exam> to Person model

- src/main/java/seedu/address/model/TaskAssignable.java
- src/main/java/seedu/address/model/group/Group.java
- src/main/java/seedu/address/model/person/Person.java
Link to #97, but will not fix it unless `LessonAssignable` is implemented.
> Add the interface `TaskAssignable`

- docs/AboutUs.md
- docs/UserGuide.md
> Fix documentation bug

- docs/UserGuide.md
> Edit User Guide to fix documentation for some commands

- src/main/java/seedu/address/logic/commands/groups/AddGroupCommand.java
- src/main/java/seedu/address/logic/commands/groups/DeleteGroupCommand.java
- src/main/java/seedu/address/logic/commands/groups/GroupAddLessonCommand.java
- src/main/java/seedu/address/logic/commands/groups/GroupRemoveLessonCommand.java
- src/main/java/seedu/address/logic/commands/persons/AddPersonCommand.java
- src/main/java/seedu/address/logic/commands/persons/EditPersonCommand.java
- src/main/java/seedu/address/logic/commands/tasks/AssignTaskToGroupCommand.java
- src/main/java/seedu/address/logic/commands/tasks/AssignTaskToPersonCommand.java
- src/main/java/seedu/address/logic/commands/tasks/DeleteTaskCommand.java
- src/main/java/seedu/address/logic/commands/tasks/EditTaskCommand.java
- src/main/java/seedu/address/logic/commands/tasks/MarkTaskDoneStudentCommand.java
- src/main/java/seedu/address/logic/commands/tasks/MarkTaskUndoneStudentCommand.java
- src/main/java/seedu/address/logic/commands/tasks/UnassignTaskFromGroupCommand.java
- src/main/java/seedu/address/logic/commands/tasks/UnassignTaskFromPersonCommand.java
- src/main/java/seedu/address/logic/parser/tasks/AddTaskCommandParser.java
- src/main/java/seedu/address/model/AddressBook.java
- src/main/java/seedu/address/model/group/GroupWithDetails.java
- src/main/java/seedu/address/model/person/Person.java
- src/main/java/seedu/address/model/person/PersonWithDetails.java
- src/main/java/seedu/address/ui/PersonViewCard.java
- src/main/java/seedu/address/ui/UiUtil.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/PersonViewCard.fxml
- src/test/java/seedu/address/logic/commands/groups/AddGroupCommandTest.java
- src/test/java/seedu/address/testutil/ModelStub.java
Fix #195 #186 #180 #151 #150
Almost all UI non-updating issues are fixed.
Edit tasks and delete tasks now change to "schedule" view.
> Fix many UI issues

- docs/UserGuide.md
- src/main/java/seedu/address/logic/commands/persons/AddPersonCommand.java
- src/main/java/seedu/address/model/group/Group.java
- src/main/java/seedu/address/model/person/Person.java
- src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
- src/test/java/seedu/address/model/person/PersonTest.java
Now the method will compare names, phone numbers, and emails. Two people are considered the same person if and only if they have the same three fields.
Fix #146.
> Change the implementation of `Person#isSamePerson()`

- docs/UserGuide.md
Update UG with student quick start tutorial.
Also added schedule command. Apparently it was missing.
Would require @kvihashini to help with some images.
> Update UG with student quick start

- docs/DeveloperGuide.md
- docs/UserGuide.md
- src/main/java/seedu/address/model/person/Exam.java
Update UG with minor bug fixes. Update DG with use case + some manual testing.
Change Exam.java toString.
> Update ug and dg

- src/test/java/seedu/address/logic/commands/groups/AddGroupCommandIntegrationTest.java
- src/test/java/seedu/address/logic/parser/groups/AddGroupCommandParserTest.java
- src/test/java/seedu/address/logic/parser/persons/PersonAddExamParserTest.java
- src/test/java/seedu/address/logic/parser/persons/PersonAddLessonParserTest.java
- src/test/java/seedu/address/logic/parser/persons/PersonRemoveExamParserTest.java
- src/test/java/seedu/address/model/lesson/LessonTest.java
- src/test/java/seedu/address/model/lesson/NoOverlapLessonListTest.java
- src/test/java/seedu/address/model/lesson/SubjectTest.java
- src/test/java/seedu/address/model/lesson/TimeslotTest.java
Just some minor improvements to my test code.
> Improve test quality for my test code

- src/main/java/seedu/address/logic/commands/tasks/AssignTaskCommand.java
- src/main/java/seedu/address/logic/commands/tasks/ManageTaskAssignmentCommand.java
- src/main/java/seedu/address/logic/commands/tasks/UnassignTaskCommand.java
> Refactor `AssignTaskCommand` and `UnassignTaskCommand`

- docs/team/eltonyeh.md
Sorry for keep pushing PPP updates, but the pdf conversion is really annoying 😠.
> Try to make ppp be in two page angrily

- docs/DeveloperGuide.md
- docs/team/tanhuakun.md
Update PP to fit page limit
Added one line in DG for manual testing.
> Update PPP to fit page limit

- docs/team/tanhuakun.md
Last PPP update. Removed many sections.
> Last PPP update.

- docs/DeveloperGuide.md
- docs/UserGuide.md
...to make the sections look nicer
> Add some page breaks for the UG and DG

- docs/UserGuide.md
> Fix grammar errors, capital casing

- docs/UserGuide.md
> Add page breaks for PDF formatting

- src/test/java/seedu/address/testutil/ModelStub.java
> Add reuse tag

- src/main/java/seedu/address/commons/core/GuiSettings.java
- src/main/java/seedu/address/logic/commands/persons/EditPersonCommand.java
- src/main/java/seedu/address/logic/parser/persons/DeletePersonCommandParser.java
Fix default UI, fix PersonDeleteCommand bug, fix indentation weirdness in one line.
> Fix minor bugs

- docs/UserGuide.md
- Change to table format for UI section
- Include INDEX notation
> Include INDEX notation inside UI section

- docs/UserGuide.md
> Fix table formatting

- docs/UserGuide.md
Add page breaks to fit content nicely in PDF.
Done again for CS2101 submission.
> Add page breaks to the UG
